In [8]:
import pandas as pd
import numpy as np
import seaborn as sns
from statistics import mean, variance

In [9]:
df1 = pd.read_csv('/content/DataSets/1_3_data_set/First_3_users_data/03. filtered_walk_label_subject128_BackHip_Accelerometer.csv')

In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
df2 = pd.read_csv('/content/DataSets/1_3_data_set/First_3_users_data/09. filtered_walk_label_subject129_BackHip_Accelerometer.csv')

In [12]:
df3 = pd.read_csv('/content/DataSets/1_3_data_set/First_3_users_data/15. filtered_walk_label_subject143_BackHip_Accelerometer.csv')

In [13]:
df1 = df1.drop(labels=['Unnamed: 0', 'datetime', 'epocms', 'elapseds'], axis=1)[:75]
df2 = df2.drop(labels=['Unnamed: 0', 'datetime', 'epocms', 'elapseds'], axis=1)[:75]
df3 = df3.drop(labels=['Unnamed: 0', 'datetime', 'epocms', 'elapseds'], axis=1)[:75]

In [14]:
df1[['x','y','z']] = df1[['lateral', 'vertical', 'anterior']]
df1 = df1.drop(labels=['lateral', 'vertical','anterior'], axis=1)

df2[['x','y','z']] = df2[['lateral', 'vertical', 'anterior']]
df2 = df2.drop(labels=['lateral', 'vertical','anterior'], axis=1)

df3[['x','y','z']] = df3[['lateral', 'vertical', 'anterior']]
df3 = df3.drop(labels=['lateral', 'vertical','anterior'], axis=1)

In [15]:
df1['label'] = 1
df1['User'] = df1['label']
df1 = df1.drop(labels='label', axis=1)

df2['label'] = 2
df2['User'] = df2['label']
df2 = df2.drop(labels='label', axis=1)

df3['label'] = 3
df3['User'] = df3['label']
df3 = df3.drop(labels='label', axis=1)

In [16]:
df1

              timestamp0500      x      y      z  User
0   2021-05-26T14.32.57.248  0.604  0.201  0.511     1
1   2021-05-26T14.32.57.259  0.595  0.050  0.554     1
2   2021-05-26T14.32.57.268  0.646 -0.116  0.567     1
3   2021-05-26T14.32.57.278  0.732 -0.254  0.533     1
4   2021-05-26T14.32.57.288  0.833 -0.314  0.528     1
..                      ...    ...    ...    ...   ...
70  2021-05-26T14.32.57.940  0.677  0.380  0.504     1
71  2021-05-26T14.32.57.949  0.578  0.362  0.444     1
72  2021-05-26T14.32.57.959  0.525  0.308  0.396     1
73  2021-05-26T14.32.57.969  0.542  0.218  0.377     1
74  2021-05-26T14.32.57.988  0.715  0.006  0.421     1

[75 rows x 5 columns]

In [17]:
df2

              timestamp0500      x      y      z  User
0   2021-05-26T16.13.02.985  0.708  0.936  0.540     2
1   2021-05-26T16.13.02.995  0.713  1.194  0.961     2
2   2021-05-26T16.13.03.004  0.839  1.055  0.369     2
3   2021-05-26T16.13.03.014  0.696  0.748  0.103     2
4   2021-05-26T16.13.03.025  0.478  0.660  0.354     2
..                      ...    ...    ...    ...   ...
70  2021-05-26T16.13.03.675  0.631  0.560  0.208     2
71  2021-05-26T16.13.03.685  0.600  0.532  0.186     2
72  2021-05-26T16.13.03.696  0.570  0.520  0.147     2
73  2021-05-26T16.13.03.706  0.571  0.480  0.128     2
74  2021-05-26T16.13.03.715  0.595  0.414  0.139     2

[75 rows x 5 columns]

In [18]:
df3

              timestamp0500      x      y      z  User
0   2021-05-26T17.35.03.729  0.959 -0.012  0.272     3
1   2021-05-26T17.35.03.738  0.995  0.054  0.361     3
2   2021-05-26T17.35.03.748  0.984  0.091  0.406     3
3   2021-05-26T17.35.03.758  0.954  0.088  0.444     3
4   2021-05-26T17.35.03.768  0.911  0.041  0.469     3
..                      ...    ...    ...    ...   ...
70  2021-05-26T17.35.04.420  0.830 -0.291  0.415     3
71  2021-05-26T17.35.04.430  0.804 -0.222  0.365     3
72  2021-05-26T17.35.04.441  0.815 -0.134  0.345     3
73  2021-05-26T17.35.04.450  0.855 -0.051  0.306     3
74  2021-05-26T17.35.04.460  0.896  0.005  0.277     3

[75 rows x 5 columns]

In [19]:
frames = df1, df2, df3
Total_Data = pd.concat(frames, axis=1)

Total_Data

,timestamp0500,x,y,z,User,timestamp0500,x,y,z,User,timestamp0500,x,y,z,User
0,2021-05-26T14.32.57.248,0.604,0.201,0.511,1,2021-05-26T16.13.02.985,0.708,0.936,0.540,2,2021-05-26T17.35.03.729,0.959,-0.012,0.272,3
1,2021-05-26T14.32.57.259,0.595,0.050,0.554,1,2021-05-26T16.13.02.995,0.713,1.194,0.961,2,2021-05-26T17.35.03.738,0.995,0.054,0.361,3
2,2021-05-26T14.32.57.268,0.646,-0.116,0.567,1,2021-05-26T16.13.03.004,0.839,1.055,0.369,2,2021-05-26T17.35.03.748,0.984,0.091,0.406,3
3,2021-05-26T14.32.57.278,0.732,-0.254,0.533,1,2021-05-26T16.13.03.014,0.696,0.748,0.103,2,2021-05-26T17.35.03.758,0.954,0.088,0.444,3
4,2021-05-26T14.32.57.288,0.833,-0.314,0.528,1,2021-05-26T16.13.03.025,0.478,0.660,0.354,2,2021-05-26T17.35.03.768,0.911,0.041,0.469,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2021-05-26T14.32.57.940,0.677,0.380,0.504,1,2021-05-26T16.13.03.675,0.631,0.560,0.208,2,2021-05-26T17.35.04.420,0.830,-0.291,0.415,3
71,2021-05-26T14.32.57.949,0.578,0.362,0.444,1,2021-05-26T16.13.03.685,0.600,0.532,0.186,2,2021-05-26T17.35.04.430,0.804,-0.222,0.365,3
72,2021-05-26T14.32.57.959,0.525,0.308,0.396,1,2021-05-26T16.13.03.696,0.570,0.520,0.147,2,2021-05-26T17.35.04.441,0.815,-0.134,0.345,3
73,2021-05-26T14.32.57.969,0.542,0.218,0.377,1,2021-05-26T16.13.03.706,0.571,0.480,0.128,2,2021-05-26T17.35.04.450,0.855,-0.051,0.306,3
74,2021-05-26T14.32.57.988,0.715,0.006,0.421,1,2021-05-26T16.13.03.715,0.595,0.414,0.139,2,2021-05-26T17.35.04.460,0.896,0.005,0.277,3

In [20]:
def data_collection(dataframe):
  count = 0
  x_acc = []
  y_acc = []
  z_acc = []
  extracted_features = []



  for value in range(len(dataframe['x'])):
    #print(value)
    if count == 4:
      avg_x = mean(x_acc)
      avg_y = mean(y_acc)
      avg_z = mean(z_acc)

      var_x = variance(x_acc)
      var_y = variance(y_acc)
      var_z = variance(z_acc)

      data_tuple = (avg_x, avg_y, avg_z, var_x, var_y, var_z)
      extracted_features.append(data_tuple)

      x_acc.clear()
      y_acc.clear()
      z_acc.clear()

      count = 0
    else:
      x_acc.append(dataframe['x'][value])
      y_acc.append(dataframe['y'][value])
      z_acc.append(dataframe['z'][value])
      count = count + 1


  return extracted_features

In [21]:
U1 = data_collection(df1)
U2 = data_collection(df2)
U3 = data_collection(df3)
features = U1, U2, U3

In [22]:
df1['x'][:4].mean(numeric_only=True)

0.64425

In [23]:
df1.describe().transpose()

      count      mean       std    min     25%    50%    75%    max
x      75.0  0.865680  0.204394  0.525  0.7315  0.833  0.915  1.416
y      75.0 -0.023573  0.179531 -0.386 -0.1290 -0.030  0.061  0.380
z      75.0  0.419440  0.207048  0.103  0.2570  0.406  0.511  1.066
User   75.0  1.000000  0.000000  1.000  1.0000  1.000  1.000  1.000

In [24]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [52]:
X = Total_Data.drop(labels=['timestamp0500', 'User'], axis=1)
y = Total_Data['User']

data_collection(Total_Data)

#for i in range(len(y)):
  #print(f"{y[i]} is equal to {X[i]}")

KeyError: ignored

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [105]:
rfc = RandomForestClassifier(n_estimators=2, max_features='auto', random_state=101)

In [106]:
rfc.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(

RandomForestClassifier(max_features='auto', n_estimators=2, random_state=101)

In [107]:
preds = rfc.predict(X_test)

In [108]:
preds, y_test

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
     User  User  User
 4      1     2     3
 63     1     2     3
 10     1     2     3
 0      1     2     3
 35     1     2     3
 61     1     2     3
 28     1     2     3
 12     1     2     3
 69     1     2     3
 64     1     2     3
 34     1     2     3
 42     1     2     3
 49     1     2     3
 18     1     2     3
 9      1     2     3)

In [36]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.multioutput import MultiOutputClassifier

In [37]:
classifier = MultiOutputClassifier(rfc)

In [56]:
x = Total_Data['x']
y = Total_Data['y']
z = Total_Data['z']

In [61]:
avg = x.mean(numeric_only=True), y.mean(numeric_only=True), z.mean(numeric_only=True)

In [67]:
x_acc = []
y_acc = []
z_acc = []
extracted_features = []



for value in range(len(X_test['x'])):
    #print(value)
    x_acc.append(mean(X_test['x'][value],X_test['y'][value],X_test['z'][value]))


print(x_acc)

KeyError: ignored

In [76]:
X_test['x']

        x      x      x
4   0.833  0.478  0.911
63  0.775  0.338  0.917
10  0.863  0.708  0.903
0   0.604  0.708  0.959
35  0.896  0.553  0.876
61  0.693  0.418  1.225
28  0.829  0.526  0.788
12  0.804  0.993  0.919
69  0.781  0.651  0.846
64  0.816  0.428  0.843
34  0.916  0.580  0.884
42  1.075  0.784  0.808
49  1.416  0.730  0.899
18  0.746  0.629  0.877
9   0.863  0.504  0.865

In [85]:
df1[['x1','y1','z1']] = df1[['x','y','z']]

In [91]:
df1 = df1.drop(labels=['x','y','z'], axis=1)

KeyError: ignored

In [93]:
df2[['x2','y2','z2']] = df2[['x','y','z']]
df3[['x3','y3', 'z3']] = df3[['x','y','z']]

df2 = df2.drop(labels=['x','y','z'], axis=1)
df3 = df3.drop(labels=['x','y','z'], axis=1)

In [97]:
finalframes = df1, df2, df3

finaldf = pd.concat(finalframes, axis=1)

In [102]:
avg_1 = finaldf['x1'].mean(numeric_only=True) + finaldf['y1'].mean(numeric_only=True) +finaldf['z1'].mean(numeric_only=True) / 3
avg_2 = finaldf['x2'].mean(numeric_only=True) + finaldf['y2'].mean(numeric_only=True) +finaldf['z2'].mean(numeric_only=True) / 3
avg_3 = finaldf['x3'].mean(numeric_only=True) + finaldf['y3'].mean(numeric_only=True) +finaldf['z3'].mean(numeric_only=True) / 3

In [103]:
totalavg = avg_1, avg_2, avg_3

In [109]:
X = finaldf.drop(labels=['timestamp0500', 'User'], axis=1)
y = finaldf['User']

In [110]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [111]:
rfc.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(

RandomForestClassifier(max_features='auto', n_estimators=2, random_state=101)

In [114]:
preds = rfc.predict(X_test)

In [115]:
preds, X_test

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
        x1     y1     z1     x2     y2     z2     x3     y3     z3
 4   0.833 -0.314  0.528  0.478  0.660  0.354  0.911  0.041  0.469
 63  0.775 -0.332  0.539  0.338  1.258  0.237  0.917 -0.207  0.426
 10  0.863 -0.030  0.451  0.708  0.485  0.485  0.903 -0.346  0.357
 0   0.604  0.201  0.511  0.708  0.936  0.540  0.959 -0.012  0.272
 35  0.896 -0.045  0.212  0.553  0.756  0.041  0.876 -0.266  0.164
 61  0.693 -0.069  0.689  0.418  1.441  0.221  1.225 -0.183  0.428
 28  0.829 -0.040  0.246  0.526  0.627  0.065  0.788 -0.236  0.208
 12  0.804  0.011  0.442  0.993  0.787  0.362  0.919 -0.309  0.297
 69  0.781  0.308  0.534  0.651  0.560  0.194  0.846 -0.317  0.438
 64  0.816 -0.386  0.519  0.428  1.120  0.260  0.843 -0.207  0.434
 34  0.916 -0.023  0.234  0.580  0.720  0.059  0.884 -0.250  0.178
 42  1.075 -0.235  0.262  0.784  0.882 -0.001  0.808 -0.227  0.080
 49  1.416  0.030  0.182  0.730  0.844  0.414  0.899 -0.288  0.019
 18  0.746 -0.012  0.388  0.629  0.682  0.237  0.877 -0.207  0.248
 9   0.863 -0.030  0.451  0.504  0.412  0.447  0.865 -0.320  0.396)

In [124]:
accuracy_score(y_test, preds)

ValueError: ignored

In [125]:
finaldf

,timestamp0500,User,x1,y1,z1,timestamp0500,User,x2,y2,z2,timestamp0500,User,x3,y3,z3
0,2021-05-26T14.32.57.248,1,0.604,0.201,0.511,2021-05-26T16.13.02.985,2,0.708,0.936,0.540,2021-05-26T17.35.03.729,3,0.959,-0.012,0.272
1,2021-05-26T14.32.57.259,1,0.595,0.050,0.554,2021-05-26T16.13.02.995,2,0.713,1.194,0.961,2021-05-26T17.35.03.738,3,0.995,0.054,0.361
2,2021-05-26T14.32.57.268,1,0.646,-0.116,0.567,2021-05-26T16.13.03.004,2,0.839,1.055,0.369,2021-05-26T17.35.03.748,3,0.984,0.091,0.406
3,2021-05-26T14.32.57.278,1,0.732,-0.254,0.533,2021-05-26T16.13.03.014,2,0.696,0.748,0.103,2021-05-26T17.35.03.758,3,0.954,0.088,0.444
4,2021-05-26T14.32.57.288,1,0.833,-0.314,0.528,2021-05-26T16.13.03.025,2,0.478,0.660,0.354,2021-05-26T17.35.03.768,3,0.911,0.041,0.469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2021-05-26T14.32.57.940,1,0.677,0.380,0.504,2021-05-26T16.13.03.675,2,0.631,0.560,0.208,2021-05-26T17.35.04.420,3,0.830,-0.291,0.415
71,2021-05-26T14.32.57.949,1,0.578,0.362,0.444,2021-05-26T16.13.03.685,2,0.600,0.532,0.186,2021-05-26T17.35.04.430,3,0.804,-0.222,0.365
72,2021-05-26T14.32.57.959,1,0.525,0.308,0.396,2021-05-26T16.13.03.696,2,0.570,0.520,0.147,2021-05-26T17.35.04.441,3,0.815,-0.134,0.345
73,2021-05-26T14.32.57.969,1,0.542,0.218,0.377,2021-05-26T16.13.03.706,2,0.571,0.480,0.128,2021-05-26T17.35.04.450,3,0.855,-0.051,0.306
74,2021-05-26T14.32.57.988,1,0.715,0.006,0.421,2021-05-26T16.13.03.715,2,0.595,0.414,0.139,2021-05-26T17.35.04.460,3,0.896,0.005,0.277